#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SHOPGIAY")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGIAY(GIAY instance);
    partial void UpdateGIAY(GIAY instance);
    partial void DeleteGIAY(GIAY instance);
    partial void InsertTHUONGHIEU(THUONGHIEU instance);
    partial void UpdateTHUONGHIEU(THUONGHIEU instance);
    partial void DeleteTHUONGHIEU(THUONGHIEU instance);
    partial void InsertHINH(HINH instance);
    partial void UpdateHINH(HINH instance);
    partial void DeleteHINH(HINH instance);
    partial void InsertHT_THANHTOAN(HT_THANHTOAN instance);
    partial void UpdateHT_THANHTOAN(HT_THANHTOAN instance);
    partial void DeleteHT_THANHTOAN(HT_THANHTOAN instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertKICHTHUOC(KICHTHUOC instance);
    partial void UpdateKICHTHUOC(KICHTHUOC instance);
    partial void DeleteKICHTHUOC(KICHTHUOC instance);
    partial void InsertLOAI(LOAI instance);
    partial void UpdateLOAI(LOAI instance);
    partial void DeleteLOAI(LOAI instance);
    partial void InsertLOAITHANHLI(LOAITHANHLI instance);
    partial void UpdateLOAITHANHLI(LOAITHANHLI instance);
    partial void DeleteLOAITHANHLI(LOAITHANHLI instance);
    partial void InsertMAUSAC(MAUSAC instance);
    partial void UpdateMAUSAC(MAUSAC instance);
    partial void DeleteMAUSAC(MAUSAC instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHIEUMUA(PHIEUMUA instance);
    partial void UpdatePHIEUMUA(PHIEUMUA instance);
    partial void DeletePHIEUMUA(PHIEUMUA instance);
    partial void InsertPHIEUNHAPKHO(PHIEUNHAPKHO instance);
    partial void UpdatePHIEUNHAPKHO(PHIEUNHAPKHO instance);
    partial void DeletePHIEUNHAPKHO(PHIEUNHAPKHO instance);
    partial void InsertPHIEUTHANHLI(PHIEUTHANHLI instance);
    partial void UpdatePHIEUTHANHLI(PHIEUTHANHLI instance);
    partial void DeletePHIEUTHANHLI(PHIEUTHANHLI instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SHOPGIAYConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GIAY> GIAYs
		{
			get
			{
				return this.GetTable<GIAY>();
			}
		}
		
		public System.Data.Linq.Table<THUONGHIEU> THUONGHIEUs
		{
			get
			{
				return this.GetTable<THUONGHIEU>();
			}
		}
		
		public System.Data.Linq.Table<HINH> HINHs
		{
			get
			{
				return this.GetTable<HINH>();
			}
		}
		
		public System.Data.Linq.Table<HT_THANHTOAN> HT_THANHTOANs
		{
			get
			{
				return this.GetTable<HT_THANHTOAN>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<KICHTHUOC> KICHTHUOCs
		{
			get
			{
				return this.GetTable<KICHTHUOC>();
			}
		}
		
		public System.Data.Linq.Table<LOAI> LOAIs
		{
			get
			{
				return this.GetTable<LOAI>();
			}
		}
		
		public System.Data.Linq.Table<LOAITHANHLI> LOAITHANHLIs
		{
			get
			{
				return this.GetTable<LOAITHANHLI>();
			}
		}
		
		public System.Data.Linq.Table<MAUSAC> MAUSACs
		{
			get
			{
				return this.GetTable<MAUSAC>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUMUA> PHIEUMUAs
		{
			get
			{
				return this.GetTable<PHIEUMUA>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUNHAPKHO> PHIEUNHAPKHOs
		{
			get
			{
				return this.GetTable<PHIEUNHAPKHO>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTHANHLI> PHIEUTHANHLIs
		{
			get
			{
				return this.GetTable<PHIEUTHANHLI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAY")]
	public partial class GIAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAGIAY;
		
		private string _TENGIAY;
		
		private System.Nullable<int> _DONGIAMUA;
		
		private System.Nullable<int> _DONGIABAN;
		
		private int _MATH;
		
		private int _MALOAI;
		
		private int _MAKICHTHUOC;
		
		private int _MAMAUSAC;
		
		private int _SOLUONG;
		
		private string _HINHANH;
		
		private string _MOTA;
		
		private EntitySet<HINH> _HINHs;
		
		private EntitySet<PHIEUMUA> _PHIEUMUAs;
		
		private EntitySet<PHIEUNHAPKHO> _PHIEUNHAPKHOs;
		
		private EntitySet<PHIEUTHANHLI> _PHIEUTHANHLIs;
		
		private EntityRef<THUONGHIEU> _THUONGHIEU;
		
		private EntityRef<KICHTHUOC> _KICHTHUOC;
		
		private EntityRef<LOAI> _LOAI;
		
		private EntityRef<MAUSAC> _MAUSAC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGIAYChanging(int value);
    partial void OnMAGIAYChanged();
    partial void OnTENGIAYChanging(string value);
    partial void OnTENGIAYChanged();
    partial void OnDONGIAMUAChanging(System.Nullable<int> value);
    partial void OnDONGIAMUAChanged();
    partial void OnDONGIABANChanging(System.Nullable<int> value);
    partial void OnDONGIABANChanged();
    partial void OnMATHChanging(int value);
    partial void OnMATHChanged();
    partial void OnMALOAIChanging(int value);
    partial void OnMALOAIChanged();
    partial void OnMAKICHTHUOCChanging(int value);
    partial void OnMAKICHTHUOCChanged();
    partial void OnMAMAUSACChanging(int value);
    partial void OnMAMAUSACChanged();
    partial void OnSOLUONGChanging(int value);
    partial void OnSOLUONGChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    #endregion
		
		public GIAY()
		{
			this._HINHs = new EntitySet<HINH>(new Action<HINH>(this.attach_HINHs), new Action<HINH>(this.detach_HINHs));
			this._PHIEUMUAs = new EntitySet<PHIEUMUA>(new Action<PHIEUMUA>(this.attach_PHIEUMUAs), new Action<PHIEUMUA>(this.detach_PHIEUMUAs));
			this._PHIEUNHAPKHOs = new EntitySet<PHIEUNHAPKHO>(new Action<PHIEUNHAPKHO>(this.attach_PHIEUNHAPKHOs), new Action<PHIEUNHAPKHO>(this.detach_PHIEUNHAPKHOs));
			this._PHIEUTHANHLIs = new EntitySet<PHIEUTHANHLI>(new Action<PHIEUTHANHLI>(this.attach_PHIEUTHANHLIs), new Action<PHIEUTHANHLI>(this.detach_PHIEUTHANHLIs));
			this._THUONGHIEU = default(EntityRef<THUONGHIEU>);
			this._KICHTHUOC = default(EntityRef<KICHTHUOC>);
			this._LOAI = default(EntityRef<LOAI>);
			this._MAUSAC = default(EntityRef<MAUSAC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAY", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAGIAY
		{
			get
			{
				return this._MAGIAY;
			}
			set
			{
				if ((this._MAGIAY != value))
				{
					this.OnMAGIAYChanging(value);
					this.SendPropertyChanging();
					this._MAGIAY = value;
					this.SendPropertyChanged("MAGIAY");
					this.OnMAGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENGIAY", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENGIAY
		{
			get
			{
				return this._TENGIAY;
			}
			set
			{
				if ((this._TENGIAY != value))
				{
					this.OnTENGIAYChanging(value);
					this.SendPropertyChanging();
					this._TENGIAY = value;
					this.SendPropertyChanged("TENGIAY");
					this.OnTENGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIAMUA", DbType="Int")]
		public System.Nullable<int> DONGIAMUA
		{
			get
			{
				return this._DONGIAMUA;
			}
			set
			{
				if ((this._DONGIAMUA != value))
				{
					this.OnDONGIAMUAChanging(value);
					this.SendPropertyChanging();
					this._DONGIAMUA = value;
					this.SendPropertyChanged("DONGIAMUA");
					this.OnDONGIAMUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIABAN", DbType="Int")]
		public System.Nullable<int> DONGIABAN
		{
			get
			{
				return this._DONGIABAN;
			}
			set
			{
				if ((this._DONGIABAN != value))
				{
					this.OnDONGIABANChanging(value);
					this.SendPropertyChanging();
					this._DONGIABAN = value;
					this.SendPropertyChanged("DONGIABAN");
					this.OnDONGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATH", DbType="Int NOT NULL")]
		public int MATH
		{
			get
			{
				return this._MATH;
			}
			set
			{
				if ((this._MATH != value))
				{
					if (this._THUONGHIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHChanging(value);
					this.SendPropertyChanging();
					this._MATH = value;
					this.SendPropertyChanged("MATH");
					this.OnMATHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Int NOT NULL")]
		public int MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					if (this._LOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKICHTHUOC", DbType="Int NOT NULL")]
		public int MAKICHTHUOC
		{
			get
			{
				return this._MAKICHTHUOC;
			}
			set
			{
				if ((this._MAKICHTHUOC != value))
				{
					if (this._KICHTHUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKICHTHUOCChanging(value);
					this.SendPropertyChanging();
					this._MAKICHTHUOC = value;
					this.SendPropertyChanged("MAKICHTHUOC");
					this.OnMAKICHTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMAUSAC", DbType="Int NOT NULL")]
		public int MAMAUSAC
		{
			get
			{
				return this._MAMAUSAC;
			}
			set
			{
				if ((this._MAMAUSAC != value))
				{
					if (this._MAUSAC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAMAUSACChanging(value);
					this.SendPropertyChanging();
					this._MAMAUSAC = value;
					this.SendPropertyChanged("MAMAUSAC");
					this.OnMAMAUSACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int NOT NULL")]
		public int SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(100)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_HINH", Storage="_HINHs", ThisKey="MAGIAY", OtherKey="MAGIAY")]
		public EntitySet<HINH> HINHs
		{
			get
			{
				return this._HINHs;
			}
			set
			{
				this._HINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_PHIEUMUA", Storage="_PHIEUMUAs", ThisKey="MAGIAY", OtherKey="MAGIAY")]
		public EntitySet<PHIEUMUA> PHIEUMUAs
		{
			get
			{
				return this._PHIEUMUAs;
			}
			set
			{
				this._PHIEUMUAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_PHIEUNHAPKHO", Storage="_PHIEUNHAPKHOs", ThisKey="MAGIAY", OtherKey="MAGIAY")]
		public EntitySet<PHIEUNHAPKHO> PHIEUNHAPKHOs
		{
			get
			{
				return this._PHIEUNHAPKHOs;
			}
			set
			{
				this._PHIEUNHAPKHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_PHIEUTHANHLI", Storage="_PHIEUTHANHLIs", ThisKey="MAGIAY", OtherKey="MAGIAY")]
		public EntitySet<PHIEUTHANHLI> PHIEUTHANHLIs
		{
			get
			{
				return this._PHIEUTHANHLIs;
			}
			set
			{
				this._PHIEUTHANHLIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONGHIEU_GIAY", Storage="_THUONGHIEU", ThisKey="MATH", OtherKey="MATH", IsForeignKey=true)]
		public THUONGHIEU THUONGHIEU
		{
			get
			{
				return this._THUONGHIEU.Entity;
			}
			set
			{
				THUONGHIEU previousValue = this._THUONGHIEU.Entity;
				if (((previousValue != value) 
							|| (this._THUONGHIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUONGHIEU.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._THUONGHIEU.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MATH = value.MATH;
					}
					else
					{
						this._MATH = default(int);
					}
					this.SendPropertyChanged("THUONGHIEU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KICHTHUOC_GIAY", Storage="_KICHTHUOC", ThisKey="MAKICHTHUOC", OtherKey="MAKICHTHUOC", IsForeignKey=true)]
		public KICHTHUOC KICHTHUOC
		{
			get
			{
				return this._KICHTHUOC.Entity;
			}
			set
			{
				KICHTHUOC previousValue = this._KICHTHUOC.Entity;
				if (((previousValue != value) 
							|| (this._KICHTHUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KICHTHUOC.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._KICHTHUOC.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MAKICHTHUOC = value.MAKICHTHUOC;
					}
					else
					{
						this._MAKICHTHUOC = default(int);
					}
					this.SendPropertyChanged("KICHTHUOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_GIAY", Storage="_LOAI", ThisKey="MALOAI", OtherKey="MALOAI", IsForeignKey=true)]
		public LOAI LOAI
		{
			get
			{
				return this._LOAI.Entity;
			}
			set
			{
				LOAI previousValue = this._LOAI.Entity;
				if (((previousValue != value) 
							|| (this._LOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAI.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._LOAI.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MALOAI = value.MALOAI;
					}
					else
					{
						this._MALOAI = default(int);
					}
					this.SendPropertyChanged("LOAI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAUSAC_GIAY", Storage="_MAUSAC", ThisKey="MAMAUSAC", OtherKey="MAMAUSAC", IsForeignKey=true)]
		public MAUSAC MAUSAC
		{
			get
			{
				return this._MAUSAC.Entity;
			}
			set
			{
				MAUSAC previousValue = this._MAUSAC.Entity;
				if (((previousValue != value) 
							|| (this._MAUSAC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAUSAC.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._MAUSAC.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MAMAUSAC = value.MAMAUSAC;
					}
					else
					{
						this._MAMAUSAC = default(int);
					}
					this.SendPropertyChanged("MAUSAC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HINHs(HINH entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = this;
		}
		
		private void detach_HINHs(HINH entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = null;
		}
		
		private void attach_PHIEUMUAs(PHIEUMUA entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = this;
		}
		
		private void detach_PHIEUMUAs(PHIEUMUA entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = null;
		}
		
		private void attach_PHIEUNHAPKHOs(PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = this;
		}
		
		private void detach_PHIEUNHAPKHOs(PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = null;
		}
		
		private void attach_PHIEUTHANHLIs(PHIEUTHANHLI entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = this;
		}
		
		private void detach_PHIEUTHANHLIs(PHIEUTHANHLI entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUONGHIEU")]
	public partial class THUONGHIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATH;
		
		private string _TENTH;
		
		private string _LOGO;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHChanging(int value);
    partial void OnMATHChanged();
    partial void OnTENTHChanging(string value);
    partial void OnTENTHChanged();
    partial void OnLOGOChanging(string value);
    partial void OnLOGOChanged();
    #endregion
		
		public THUONGHIEU()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATH
		{
			get
			{
				return this._MATH;
			}
			set
			{
				if ((this._MATH != value))
				{
					this.OnMATHChanging(value);
					this.SendPropertyChanging();
					this._MATH = value;
					this.SendPropertyChanged("MATH");
					this.OnMATHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TENTH
		{
			get
			{
				return this._TENTH;
			}
			set
			{
				if ((this._TENTH != value))
				{
					this.OnTENTHChanging(value);
					this.SendPropertyChanging();
					this._TENTH = value;
					this.SendPropertyChanged("TENTH");
					this.OnTENTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGO", DbType="NVarChar(100)")]
		public string LOGO
		{
			get
			{
				return this._LOGO;
			}
			set
			{
				if ((this._LOGO != value))
				{
					this.OnLOGOChanging(value);
					this.SendPropertyChanging();
					this._LOGO = value;
					this.SendPropertyChanged("LOGO");
					this.OnLOGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONGHIEU_GIAY", Storage="_GIAYs", ThisKey="MATH", OtherKey="MATH")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.THUONGHIEU = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.THUONGHIEU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HINH")]
	public partial class HINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHINH;
		
		private int _MAGIAY;
		
		private string _HINH1;
		
		private EntityRef<GIAY> _GIAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHINHChanging(int value);
    partial void OnMAHINHChanged();
    partial void OnMAGIAYChanging(int value);
    partial void OnMAGIAYChanged();
    partial void OnHINH1Changing(string value);
    partial void OnHINH1Changed();
    #endregion
		
		public HINH()
		{
			this._GIAY = default(EntityRef<GIAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHINH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAHINH
		{
			get
			{
				return this._MAHINH;
			}
			set
			{
				if ((this._MAHINH != value))
				{
					this.OnMAHINHChanging(value);
					this.SendPropertyChanging();
					this._MAHINH = value;
					this.SendPropertyChanged("MAHINH");
					this.OnMAHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAY", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAGIAY
		{
			get
			{
				return this._MAGIAY;
			}
			set
			{
				if ((this._MAGIAY != value))
				{
					if (this._GIAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGIAYChanging(value);
					this.SendPropertyChanging();
					this._MAGIAY = value;
					this.SendPropertyChanged("MAGIAY");
					this.OnMAGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="HINH", Storage="_HINH1", DbType="NVarChar(100)")]
		public string HINH1
		{
			get
			{
				return this._HINH1;
			}
			set
			{
				if ((this._HINH1 != value))
				{
					this.OnHINH1Changing(value);
					this.SendPropertyChanging();
					this._HINH1 = value;
					this.SendPropertyChanged("HINH1");
					this.OnHINH1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_HINH", Storage="_GIAY", ThisKey="MAGIAY", OtherKey="MAGIAY", IsForeignKey=true)]
		public GIAY GIAY
		{
			get
			{
				return this._GIAY.Entity;
			}
			set
			{
				GIAY previousValue = this._GIAY.Entity;
				if (((previousValue != value) 
							|| (this._GIAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAY.Entity = null;
						previousValue.HINHs.Remove(this);
					}
					this._GIAY.Entity = value;
					if ((value != null))
					{
						value.HINHs.Add(this);
						this._MAGIAY = value.MAGIAY;
					}
					else
					{
						this._MAGIAY = default(int);
					}
					this.SendPropertyChanged("GIAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HT_THANHTOAN")]
	public partial class HT_THANHTOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATT;
		
		private string _TENTT;
		
		private EntitySet<PHIEUMUA> _PHIEUMUAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATTChanging(int value);
    partial void OnMATTChanged();
    partial void OnTENTTChanging(string value);
    partial void OnTENTTChanged();
    #endregion
		
		public HT_THANHTOAN()
		{
			this._PHIEUMUAs = new EntitySet<PHIEUMUA>(new Action<PHIEUMUA>(this.attach_PHIEUMUAs), new Action<PHIEUMUA>(this.detach_PHIEUMUAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATT
		{
			get
			{
				return this._MATT;
			}
			set
			{
				if ((this._MATT != value))
				{
					this.OnMATTChanging(value);
					this.SendPropertyChanging();
					this._MATT = value;
					this.SendPropertyChanged("MATT");
					this.OnMATTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTT", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENTT
		{
			get
			{
				return this._TENTT;
			}
			set
			{
				if ((this._TENTT != value))
				{
					this.OnTENTTChanging(value);
					this.SendPropertyChanging();
					this._TENTT = value;
					this.SendPropertyChanged("TENTT");
					this.OnTENTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_THANHTOAN_PHIEUMUA", Storage="_PHIEUMUAs", ThisKey="MATT", OtherKey="MATT")]
		public EntitySet<PHIEUMUA> PHIEUMUAs
		{
			get
			{
				return this._PHIEUMUAs;
			}
			set
			{
				this._PHIEUMUAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUMUAs(PHIEUMUA entity)
		{
			this.SendPropertyChanging();
			entity.HT_THANHTOAN = this;
		}
		
		private void detach_PHIEUMUAs(PHIEUMUA entity)
		{
			this.SendPropertyChanging();
			entity.HT_THANHTOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKH;
		
		private string _HOTENKH;
		
		private string _DIENTHOAI;
		
		private string _DIACHI;
		
		private string _TENDNKH;
		
		private string _MATKHAUKH;
		
		private string _EMAIL;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _HINHANH;
		
		private EntitySet<PHIEUMUA> _PHIEUMUAs;
		
		private EntitySet<PHIEUTHANHLI> _PHIEUTHANHLIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHChanging(int value);
    partial void OnMAKHChanged();
    partial void OnHOTENKHChanging(string value);
    partial void OnHOTENKHChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnTENDNKHChanging(string value);
    partial void OnTENDNKHChanged();
    partial void OnMATKHAUKHChanging(string value);
    partial void OnMATKHAUKHChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._PHIEUMUAs = new EntitySet<PHIEUMUA>(new Action<PHIEUMUA>(this.attach_PHIEUMUAs), new Action<PHIEUMUA>(this.detach_PHIEUMUAs));
			this._PHIEUTHANHLIs = new EntitySet<PHIEUTHANHLI>(new Action<PHIEUTHANHLI>(this.attach_PHIEUTHANHLIs), new Action<PHIEUTHANHLI>(this.detach_PHIEUTHANHLIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENKH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string HOTENKH
		{
			get
			{
				return this._HOTENKH;
			}
			set
			{
				if ((this._HOTENKH != value))
				{
					this.OnHOTENKHChanging(value);
					this.SendPropertyChanging();
					this._HOTENKH = value;
					this.SendPropertyChanged("HOTENKH");
					this.OnHOTENKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(200)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDNKH", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TENDNKH
		{
			get
			{
				return this._TENDNKH;
			}
			set
			{
				if ((this._TENDNKH != value))
				{
					this.OnTENDNKHChanging(value);
					this.SendPropertyChanging();
					this._TENDNKH = value;
					this.SendPropertyChanged("TENDNKH");
					this.OnTENDNKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAUKH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MATKHAUKH
		{
			get
			{
				return this._MATKHAUKH;
			}
			set
			{
				if ((this._MATKHAUKH != value))
				{
					this.OnMATKHAUKHChanging(value);
					this.SendPropertyChanging();
					this._MATKHAUKH = value;
					this.SendPropertyChanged("MATKHAUKH");
					this.OnMATKHAUKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(200)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUMUA", Storage="_PHIEUMUAs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<PHIEUMUA> PHIEUMUAs
		{
			get
			{
				return this._PHIEUMUAs;
			}
			set
			{
				this._PHIEUMUAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUTHANHLI", Storage="_PHIEUTHANHLIs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<PHIEUTHANHLI> PHIEUTHANHLIs
		{
			get
			{
				return this._PHIEUTHANHLIs;
			}
			set
			{
				this._PHIEUTHANHLIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUMUAs(PHIEUMUA entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_PHIEUMUAs(PHIEUMUA entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_PHIEUTHANHLIs(PHIEUTHANHLI entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_PHIEUTHANHLIs(PHIEUTHANHLI entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KICHTHUOC")]
	public partial class KICHTHUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKICHTHUOC;
		
		private int _TENKICHTHUOC;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKICHTHUOCChanging(int value);
    partial void OnMAKICHTHUOCChanged();
    partial void OnTENKICHTHUOCChanging(int value);
    partial void OnTENKICHTHUOCChanged();
    #endregion
		
		public KICHTHUOC()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKICHTHUOC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAKICHTHUOC
		{
			get
			{
				return this._MAKICHTHUOC;
			}
			set
			{
				if ((this._MAKICHTHUOC != value))
				{
					this.OnMAKICHTHUOCChanging(value);
					this.SendPropertyChanging();
					this._MAKICHTHUOC = value;
					this.SendPropertyChanged("MAKICHTHUOC");
					this.OnMAKICHTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKICHTHUOC", DbType="Int NOT NULL")]
		public int TENKICHTHUOC
		{
			get
			{
				return this._TENKICHTHUOC;
			}
			set
			{
				if ((this._TENKICHTHUOC != value))
				{
					this.OnTENKICHTHUOCChanging(value);
					this.SendPropertyChanging();
					this._TENKICHTHUOC = value;
					this.SendPropertyChanged("TENKICHTHUOC");
					this.OnTENKICHTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KICHTHUOC_GIAY", Storage="_GIAYs", ThisKey="MAKICHTHUOC", OtherKey="MAKICHTHUOC")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.KICHTHUOC = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.KICHTHUOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI")]
	public partial class LOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALOAI;
		
		private string _TENLOAI;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIChanging(int value);
    partial void OnMALOAIChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    #endregion
		
		public LOAI()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_GIAY", Storage="_GIAYs", ThisKey="MALOAI", OtherKey="MALOAI")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAI = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAITHANHLI")]
	public partial class LOAITHANHLI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALOAITL;
		
		private string _TENLOAITL;
		
		private int _GIA;
		
		private EntitySet<PHIEUTHANHLI> _PHIEUTHANHLIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAITLChanging(int value);
    partial void OnMALOAITLChanged();
    partial void OnTENLOAITLChanging(string value);
    partial void OnTENLOAITLChanged();
    partial void OnGIAChanging(int value);
    partial void OnGIAChanged();
    #endregion
		
		public LOAITHANHLI()
		{
			this._PHIEUTHANHLIs = new EntitySet<PHIEUTHANHLI>(new Action<PHIEUTHANHLI>(this.attach_PHIEUTHANHLIs), new Action<PHIEUTHANHLI>(this.detach_PHIEUTHANHLIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAITL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MALOAITL
		{
			get
			{
				return this._MALOAITL;
			}
			set
			{
				if ((this._MALOAITL != value))
				{
					this.OnMALOAITLChanging(value);
					this.SendPropertyChanging();
					this._MALOAITL = value;
					this.SendPropertyChanged("MALOAITL");
					this.OnMALOAITLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAITL", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TENLOAITL
		{
			get
			{
				return this._TENLOAITL;
			}
			set
			{
				if ((this._TENLOAITL != value))
				{
					this.OnTENLOAITLChanging(value);
					this.SendPropertyChanging();
					this._TENLOAITL = value;
					this.SendPropertyChanged("TENLOAITL");
					this.OnTENLOAITLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA", DbType="Int NOT NULL")]
		public int GIA
		{
			get
			{
				return this._GIA;
			}
			set
			{
				if ((this._GIA != value))
				{
					this.OnGIAChanging(value);
					this.SendPropertyChanging();
					this._GIA = value;
					this.SendPropertyChanged("GIA");
					this.OnGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHANHLI_PHIEUTHANHLI", Storage="_PHIEUTHANHLIs", ThisKey="MALOAITL", OtherKey="MALOAITL")]
		public EntitySet<PHIEUTHANHLI> PHIEUTHANHLIs
		{
			get
			{
				return this._PHIEUTHANHLIs;
			}
			set
			{
				this._PHIEUTHANHLIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUTHANHLIs(PHIEUTHANHLI entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHANHLI = this;
		}
		
		private void detach_PHIEUTHANHLIs(PHIEUTHANHLI entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHANHLI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAUSAC")]
	public partial class MAUSAC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAMAUSAC;
		
		private string _TENMAUSAC;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAMAUSACChanging(int value);
    partial void OnMAMAUSACChanged();
    partial void OnTENMAUSACChanging(string value);
    partial void OnTENMAUSACChanged();
    #endregion
		
		public MAUSAC()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMAUSAC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAMAUSAC
		{
			get
			{
				return this._MAMAUSAC;
			}
			set
			{
				if ((this._MAMAUSAC != value))
				{
					this.OnMAMAUSACChanging(value);
					this.SendPropertyChanging();
					this._MAMAUSAC = value;
					this.SendPropertyChanged("MAMAUSAC");
					this.OnMAMAUSACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMAUSAC", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TENMAUSAC
		{
			get
			{
				return this._TENMAUSAC;
			}
			set
			{
				if ((this._TENMAUSAC != value))
				{
					this.OnTENMAUSACChanging(value);
					this.SendPropertyChanging();
					this._TENMAUSAC = value;
					this.SendPropertyChanged("TENMAUSAC");
					this.OnTENMAUSACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAUSAC_GIAY", Storage="_GIAYs", ThisKey="MAMAUSAC", OtherKey="MAMAUSAC")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.MAUSAC = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.MAUSAC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANV;
		
		private string _HOTENNV;
		
		private string _GIOITINH;
		
		private System.DateTime _NGAYSINH;
		
		private string _DIACHI;
		
		private string _DIENTHOAI;
		
		private System.Nullable<int> _LUONG;
		
		private string _TENLOAINV;
		
		private string _TENDN;
		
		private string _MATKHAU;
		
		private string _HINHANH;
		
		private EntitySet<PHIEUNHAPKHO> _PHIEUNHAPKHOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(int value);
    partial void OnMANVChanged();
    partial void OnHOTENNVChanging(string value);
    partial void OnHOTENNVChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNGAYSINHChanging(System.DateTime value);
    partial void OnNGAYSINHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnLUONGChanging(System.Nullable<int> value);
    partial void OnLUONGChanged();
    partial void OnTENLOAINVChanging(string value);
    partial void OnTENLOAINVChanged();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._PHIEUNHAPKHOs = new EntitySet<PHIEUNHAPKHO>(new Action<PHIEUNHAPKHO>(this.attach_PHIEUNHAPKHOs), new Action<PHIEUNHAPKHO>(this.detach_PHIEUNHAPKHOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENNV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string HOTENNV
		{
			get
			{
				return this._HOTENNV;
			}
			set
			{
				if ((this._HOTENNV != value))
				{
					this.OnHOTENNVChanging(value);
					this.SendPropertyChanging();
					this._HOTENNV = value;
					this.SendPropertyChanged("HOTENNV");
					this.OnHOTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUONG", DbType="Int")]
		public System.Nullable<int> LUONG
		{
			get
			{
				return this._LUONG;
			}
			set
			{
				if ((this._LUONG != value))
				{
					this.OnLUONGChanging(value);
					this.SendPropertyChanging();
					this._LUONG = value;
					this.SendPropertyChanged("LUONG");
					this.OnLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAINV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENLOAINV
		{
			get
			{
				return this._TENLOAINV;
			}
			set
			{
				if ((this._TENLOAINV != value))
				{
					this.OnTENLOAINVChanging(value);
					this.SendPropertyChanging();
					this._TENLOAINV = value;
					this.SendPropertyChanged("TENLOAINV");
					this.OnTENLOAINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUNHAPKHO", Storage="_PHIEUNHAPKHOs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<PHIEUNHAPKHO> PHIEUNHAPKHOs
		{
			get
			{
				return this._PHIEUNHAPKHOs;
			}
			set
			{
				this._PHIEUNHAPKHOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUNHAPKHOs(PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUNHAPKHOs(PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUMUA")]
	public partial class PHIEUMUA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPHIEUDH;
		
		private int _MAKH;
		
		private int _MATT;
		
		private int _MAGIAY;
		
		private System.DateTime _NGAYLAP;
		
		private System.Nullable<int> _TONGTIEN;
		
		private System.Nullable<bool> _DATHANHTOAN;
		
		private EntityRef<GIAY> _GIAY;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<HT_THANHTOAN> _HT_THANHTOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUDHChanging(int value);
    partial void OnMAPHIEUDHChanged();
    partial void OnMAKHChanging(int value);
    partial void OnMAKHChanged();
    partial void OnMATTChanging(int value);
    partial void OnMATTChanged();
    partial void OnMAGIAYChanging(int value);
    partial void OnMAGIAYChanged();
    partial void OnNGAYLAPChanging(System.DateTime value);
    partial void OnNGAYLAPChanged();
    partial void OnTONGTIENChanging(System.Nullable<int> value);
    partial void OnTONGTIENChanged();
    partial void OnDATHANHTOANChanging(System.Nullable<bool> value);
    partial void OnDATHANHTOANChanged();
    #endregion
		
		public PHIEUMUA()
		{
			this._GIAY = default(EntityRef<GIAY>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._HT_THANHTOAN = default(EntityRef<HT_THANHTOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUDH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEUDH
		{
			get
			{
				return this._MAPHIEUDH;
			}
			set
			{
				if ((this._MAPHIEUDH != value))
				{
					this.OnMAPHIEUDHChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUDH = value;
					this.SendPropertyChanged("MAPHIEUDH");
					this.OnMAPHIEUDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="Int NOT NULL")]
		public int MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATT", DbType="Int NOT NULL")]
		public int MATT
		{
			get
			{
				return this._MATT;
			}
			set
			{
				if ((this._MATT != value))
				{
					if (this._HT_THANHTOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATTChanging(value);
					this.SendPropertyChanging();
					this._MATT = value;
					this.SendPropertyChanged("MATT");
					this.OnMATTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAY", DbType="Int NOT NULL")]
		public int MAGIAY
		{
			get
			{
				return this._MAGIAY;
			}
			set
			{
				if ((this._MAGIAY != value))
				{
					if (this._GIAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGIAYChanging(value);
					this.SendPropertyChanging();
					this._MAGIAY = value;
					this.SendPropertyChanged("MAGIAY");
					this.OnMAGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Int")]
		public System.Nullable<int> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATHANHTOAN", DbType="Bit")]
		public System.Nullable<bool> DATHANHTOAN
		{
			get
			{
				return this._DATHANHTOAN;
			}
			set
			{
				if ((this._DATHANHTOAN != value))
				{
					this.OnDATHANHTOANChanging(value);
					this.SendPropertyChanging();
					this._DATHANHTOAN = value;
					this.SendPropertyChanged("DATHANHTOAN");
					this.OnDATHANHTOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_PHIEUMUA", Storage="_GIAY", ThisKey="MAGIAY", OtherKey="MAGIAY", IsForeignKey=true)]
		public GIAY GIAY
		{
			get
			{
				return this._GIAY.Entity;
			}
			set
			{
				GIAY previousValue = this._GIAY.Entity;
				if (((previousValue != value) 
							|| (this._GIAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAY.Entity = null;
						previousValue.PHIEUMUAs.Remove(this);
					}
					this._GIAY.Entity = value;
					if ((value != null))
					{
						value.PHIEUMUAs.Add(this);
						this._MAGIAY = value.MAGIAY;
					}
					else
					{
						this._MAGIAY = default(int);
					}
					this.SendPropertyChanged("GIAY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUMUA", Storage="_KHACHHANG", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.PHIEUMUAs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.PHIEUMUAs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HT_THANHTOAN_PHIEUMUA", Storage="_HT_THANHTOAN", ThisKey="MATT", OtherKey="MATT", IsForeignKey=true)]
		public HT_THANHTOAN HT_THANHTOAN
		{
			get
			{
				return this._HT_THANHTOAN.Entity;
			}
			set
			{
				HT_THANHTOAN previousValue = this._HT_THANHTOAN.Entity;
				if (((previousValue != value) 
							|| (this._HT_THANHTOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HT_THANHTOAN.Entity = null;
						previousValue.PHIEUMUAs.Remove(this);
					}
					this._HT_THANHTOAN.Entity = value;
					if ((value != null))
					{
						value.PHIEUMUAs.Add(this);
						this._MATT = value.MATT;
					}
					else
					{
						this._MATT = default(int);
					}
					this.SendPropertyChanged("HT_THANHTOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUNHAPKHO")]
	public partial class PHIEUNHAPKHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPHIEUNK;
		
		private System.DateTime _NGAYNK;
		
		private int _MANV;
		
		private int _MAGIAY;
		
		private EntityRef<GIAY> _GIAY;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUNKChanging(int value);
    partial void OnMAPHIEUNKChanged();
    partial void OnNGAYNKChanging(System.DateTime value);
    partial void OnNGAYNKChanged();
    partial void OnMANVChanging(int value);
    partial void OnMANVChanged();
    partial void OnMAGIAYChanging(int value);
    partial void OnMAGIAYChanged();
    #endregion
		
		public PHIEUNHAPKHO()
		{
			this._GIAY = default(EntityRef<GIAY>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUNK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEUNK
		{
			get
			{
				return this._MAPHIEUNK;
			}
			set
			{
				if ((this._MAPHIEUNK != value))
				{
					this.OnMAPHIEUNKChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUNK = value;
					this.SendPropertyChanged("MAPHIEUNK");
					this.OnMAPHIEUNKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNK", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYNK
		{
			get
			{
				return this._NGAYNK;
			}
			set
			{
				if ((this._NGAYNK != value))
				{
					this.OnNGAYNKChanging(value);
					this.SendPropertyChanging();
					this._NGAYNK = value;
					this.SendPropertyChanged("NGAYNK");
					this.OnNGAYNKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int NOT NULL")]
		public int MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAY", DbType="Int NOT NULL")]
		public int MAGIAY
		{
			get
			{
				return this._MAGIAY;
			}
			set
			{
				if ((this._MAGIAY != value))
				{
					if (this._GIAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGIAYChanging(value);
					this.SendPropertyChanging();
					this._MAGIAY = value;
					this.SendPropertyChanged("MAGIAY");
					this.OnMAGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_PHIEUNHAPKHO", Storage="_GIAY", ThisKey="MAGIAY", OtherKey="MAGIAY", IsForeignKey=true)]
		public GIAY GIAY
		{
			get
			{
				return this._GIAY.Entity;
			}
			set
			{
				GIAY previousValue = this._GIAY.Entity;
				if (((previousValue != value) 
							|| (this._GIAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAY.Entity = null;
						previousValue.PHIEUNHAPKHOs.Remove(this);
					}
					this._GIAY.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPKHOs.Add(this);
						this._MAGIAY = value.MAGIAY;
					}
					else
					{
						this._MAGIAY = default(int);
					}
					this.SendPropertyChanged("GIAY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUNHAPKHO", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUNHAPKHOs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPKHOs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(int);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTHANHLI")]
	public partial class PHIEUTHANHLI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPHIEUTL;
		
		private int _MAGIAY;
		
		private int _MAKH;
		
		private int _MALOAITL;
		
		private System.DateTime _NGAYTHANHLI;
		
		private EntityRef<GIAY> _GIAY;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<LOAITHANHLI> _LOAITHANHLI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUTLChanging(int value);
    partial void OnMAPHIEUTLChanged();
    partial void OnMAGIAYChanging(int value);
    partial void OnMAGIAYChanged();
    partial void OnMAKHChanging(int value);
    partial void OnMAKHChanged();
    partial void OnMALOAITLChanging(int value);
    partial void OnMALOAITLChanged();
    partial void OnNGAYTHANHLIChanging(System.DateTime value);
    partial void OnNGAYTHANHLIChanged();
    #endregion
		
		public PHIEUTHANHLI()
		{
			this._GIAY = default(EntityRef<GIAY>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._LOAITHANHLI = default(EntityRef<LOAITHANHLI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUTL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEUTL
		{
			get
			{
				return this._MAPHIEUTL;
			}
			set
			{
				if ((this._MAPHIEUTL != value))
				{
					this.OnMAPHIEUTLChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUTL = value;
					this.SendPropertyChanged("MAPHIEUTL");
					this.OnMAPHIEUTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAY", DbType="Int NOT NULL")]
		public int MAGIAY
		{
			get
			{
				return this._MAGIAY;
			}
			set
			{
				if ((this._MAGIAY != value))
				{
					if (this._GIAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGIAYChanging(value);
					this.SendPropertyChanging();
					this._MAGIAY = value;
					this.SendPropertyChanged("MAGIAY");
					this.OnMAGIAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="Int NOT NULL")]
		public int MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAITL", DbType="Int NOT NULL")]
		public int MALOAITL
		{
			get
			{
				return this._MALOAITL;
			}
			set
			{
				if ((this._MALOAITL != value))
				{
					if (this._LOAITHANHLI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAITLChanging(value);
					this.SendPropertyChanging();
					this._MALOAITL = value;
					this.SendPropertyChanged("MALOAITL");
					this.OnMALOAITLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHANHLI", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYTHANHLI
		{
			get
			{
				return this._NGAYTHANHLI;
			}
			set
			{
				if ((this._NGAYTHANHLI != value))
				{
					this.OnNGAYTHANHLIChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHANHLI = value;
					this.SendPropertyChanged("NGAYTHANHLI");
					this.OnNGAYTHANHLIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_PHIEUTHANHLI", Storage="_GIAY", ThisKey="MAGIAY", OtherKey="MAGIAY", IsForeignKey=true)]
		public GIAY GIAY
		{
			get
			{
				return this._GIAY.Entity;
			}
			set
			{
				GIAY previousValue = this._GIAY.Entity;
				if (((previousValue != value) 
							|| (this._GIAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAY.Entity = null;
						previousValue.PHIEUTHANHLIs.Remove(this);
					}
					this._GIAY.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHANHLIs.Add(this);
						this._MAGIAY = value.MAGIAY;
					}
					else
					{
						this._MAGIAY = default(int);
					}
					this.SendPropertyChanged("GIAY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUTHANHLI", Storage="_KHACHHANG", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.PHIEUTHANHLIs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHANHLIs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHANHLI_PHIEUTHANHLI", Storage="_LOAITHANHLI", ThisKey="MALOAITL", OtherKey="MALOAITL", IsForeignKey=true)]
		public LOAITHANHLI LOAITHANHLI
		{
			get
			{
				return this._LOAITHANHLI.Entity;
			}
			set
			{
				LOAITHANHLI previousValue = this._LOAITHANHLI.Entity;
				if (((previousValue != value) 
							|| (this._LOAITHANHLI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITHANHLI.Entity = null;
						previousValue.PHIEUTHANHLIs.Remove(this);
					}
					this._LOAITHANHLI.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHANHLIs.Add(this);
						this._MALOAITL = value.MALOAITL;
					}
					else
					{
						this._MALOAITL = default(int);
					}
					this.SendPropertyChanged("LOAITHANHLI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
